[package]
name = "shop_macro"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
lalrpop-util = "0.19.7"
regex = "1"

[dependencies.strecklistan_api]
path = "../common"

[build-dependencies]
lalrpop = "0.19.7"
